# ARG DOCKER_PYTHON_VERSION=3.9-slim-bullseye 
ARG DOCKER_PYTHON_VERSION=3.9.16-slim-buster
FROM python:$DOCKER_PYTHON_VERSION

ARG UNAME=apiuser
ARG UID=1000
ARG GID=1000

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 PYTHONUNBUFFERED=1

WORKDIR /
COPY requirements.txt ./
RUN python -m pip install --no-cache-dir --upgrade pip 
RUN python -m pip install --no-cache-dir celery==5.2.2
RUN python -m pip install --no-cache-dir Django==3.2.12
RUN python -m pip install --no-cache-dir django-settings-export==1.2.1
RUN python -m pip install --no-cache-dir djangorestframework==3.13.1
RUN python -m pip install --no-cache-dir djangorestframework-jsonp==1.0.2
RUN python -m pip install --no-cache-dir djangorestframework-simplejwt==5.0.0
RUN python -m pip install --no-cache-dir djangorestframework-xml==2.0.0
RUN python -m pip install --no-cache-dir djangorestframework-yaml==2.0.0
RUN python -m pip install --no-cache-dir PyJWT==2.3.0
RUN python -m pip install --no-cache-dir pymongo==3.12.3
RUN python -m pip install --no-cache-dir python-memcached==1.59
RUN python -m pip install --no-cache-dir pytz==2021.3
RUN python -m pip install --no-cache-dir PyYAML==6.0
RUN python -m pip install --no-cache-dir gunicorn==20.1.0
RUN rm requirements.txt

COPY . /app
WORKDIR /app

#Setup API User
RUN groupadd -g $GID -o $UNAME \
  &&  useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME \
  && chown $UNAME:$UNAME -R /app

USER $UNAME

EXPOSE 8080
CMD ["gunicorn", "--config=gunicorn.py", "api.wsgi:application"]
