From ubuntu:20.04
# From r-base
# From python:3.9.13
ARG CELERY_SSH_USER 

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
	apt-get install -y  openssh-server \
	gfortran \
	vim \
	python3 python3-pip

RUN pip install --no-cache-dir --upgrade pip && \
	pip install --no-cache-dir numpy pyyaml==6.0.* --index-url https://pypi.tuna.tsinghua.edu.cn/simple
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt --index-url https://pypi.tuna.tsinghua.edu.cn/simple

# RUN Rscript -e "install.packages('ggplot2',dependencies=TRUE, repos='http://cran.rstudio.com/')" 
# RUN Rscript -e "install.packages('readxl',dependencies=TRUE, repos='http://cran.rstudio.com/')" 
# RUN Rscript -e "install.packages('zoo',dependencies=TRUE, repos='http://cran.rstudio.com/')" 
# RUN Rscript -e "install.packages('rstudioapi',dependencies=TRUE, repos='http://cran.rstudio.com/')" 
# RUN Rscript -e "install.packages('magrittr',dependencies=TRUE, repos='http://cran.rstudio.com/')" 
# RUN Rscript -e "install.packages('reshape',dependencies=TRUE, repos='http://cran.rstudio.com/')" 
# RUN Rscript -e "install.packages('gridExtra',dependencies=TRUE, repos='http://cran.rstudio.com/')" 
# RUN Rscript -e "install.packages('stringr',dependencies=TRUE, repos='http://cran.rstudio.com/')" 

RUN mkdir /var/run/sshd 

RUN useradd -r -U -m $CELERY_SSH_USER && \
	chown -R $CELERY_SSH_USER:$CELERY_SSH_USER /home/$CELERY_SSH_USER 

EXPOSE 22

WORKDIR /home/$CELERY_SSH_USER
USER $CELERY_SSH_USER

# COPY test.f90 .
# COPY test.f90 .
# RUN gfortran -o test test.f90

RUN mkdir models
COPY ./models ./models
COPY run.py .
COPY default_setting.yml .


RUN gfortran -o test ./models/teco_spruce/test.f90 

RUN mkdir input
COPY ./input ./input

RUN mkdir output
COPY ./output ./output

# COPY test_R.r .

USER root

COPY start_sshd.sh /root/ 
COPY entrypoint.sh entrypoint.sh
CMD ["/bin/sh", "entrypoint.sh"]
# CMD ["/input/SPRUCE_pars.txt", "/input/SPRUCE_forcing.txt", "/input/SPRUCE_obs.txt", "/source/output/", "0"]
